export type { Link, Image, StatItem } from './common';
export type {
  HeroSection,
  HeroSectionData,
  HeroSnapshot,
  HeroSnapshotStat,
  ProjectsSection,
  ProjectsSectionData,
  Project,
  AboutSection,
  AboutSectionData,
  AboutFeature,
  AboutCoreStack,
  AboutJourney,
  AboutStat,
  ContactSection,
  ContactSectionData,
  ContactChannel,
  ContactChannelKind,
  ContactDetail,
  ContactFooter,
  ExperienceSection,
  ExperienceSectionData,
  ExperienceItem,
  InitiativesSection,
  InitiativesSectionData,
  InitiativeItem,
} from './sections';
export type { SectionType, Section, PageMetadata, PageContent } from './content';
